apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.port }}
      targetPort: {{ .Values.deployment.port }}
  type: {{ .Values.service.type }}
