apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  namespace: {{ .Values.namespace }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.parameters.type }}  # general purpose SSD (gp3, gp2)
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }} 
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }} 
